name: autotools

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install packages
      run: sudo apt install libleptonica-dev

    - name: Checkout Tesseract
      uses: actions/checkout@v4
      with:
        repository: tesseract-ocr/tesseract
        ref: 5.2.0

    - name: Setup Tesseract
      run: ./autogen.sh

    - name: Configure Tesseract
      run: ./configure '--disable-openmp' '--disable-doc' 'CXXFLAGS=-g -O2'

    - name: Make Tesseract
      run: make

    - name: Install Tesseract
      run: sudo make install

    - name: Upload Tesseract artifact
      uses: actions/upload-artifact@v4
      with:
        name: tesseract-build
        path: /usr/local/lib/libtesseract.so.5.0.2

    - name: Upload Leptonica artifact
      uses: actions/upload-artifact@v4
      with:
        name: leptonica-build
        path: /usr/lib/x86_64-linux-gnu/liblept.so.5.0.4
