name: autotools

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install automake ca-certificates g++ git libtool libleptonica-dev make pkg-config

    - name: Checkout Tesseract
      uses: actions/checkout@v4
      with:
        repository: tesseract-ocr/tesseract
        ref: 5.2.0
    
    - name: Build Tesseract
      run: |
        ./autogen.sh
        ./configure --prefix=../tesseract-build/
        make
        sudo make install
    - name: Archive Tesseract
      uses: actions/upload-artifact@v4
      with:
        name: tesserac-build
        path: ../tesseract-build/
