# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build dependencies

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-leptonica-windows:

    runs-on: windows-latest

    steps:
    - run: vcpkg install giflib:x86-windows-static libjpeg-turbo:x86-windows-static liblzma:x86-windows-static libpng:x86-windows-static tiff:x86-windows-static zlib:x86-windows-static
    - run: vcpkg install giflib:x64-windows-static libjpeg-turbo:x64-windows-static liblzma:x64-windows-static libpng:x64-windows-static tiff:x64-windows-static zlib:x64-windows-static
    - uses: actions/checkout@v4
      with:
        repository: 'DanBloomberg/leptonica'
        ref: '1.82.0'
    - run: mkdir vs17-x86
    - run: cmake .. -G "Visual Studio 17 2022" -A Win32 -DSW_BUILD=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_TOOLCHAIN_FILE=%VCPKG_HOME%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows-static -DCMAKE_INSTALL_PREFIX=..\..\build\x86
      working_direcotry: vs17-x86
    - run: cmake --build . --config Release --target install
      working_direcotry: vs17-x86
    - run: mkdir vs17-x64
    - run: cmake .. -G "Visual Studio 17 2022" -A x64 -DSW_BUILD=OFF -DBUILD_SHARED_LIBS=ON  -DCMAKE_TOOLCHAIN_FILE=%VCPKG_HOME%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_INSTALL_PREFIX=..\..\build\x64
      working_direcotry: vs17-x64
    - run: cmake --build . --config Release --target install
      working_direcotry: vs17-x64

  build-tesseract-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'tesseract-ocr/tesseract'
        ref: '5.2.0'
    - run: mkdir vs17-x86
    - run: cmake .. -G "Visual Studio 17 2022" -A Win32 -DAUTO_OPTIMIZE=OFF -DSW_BUILD=OFF -DBUILD_TRAINING_TOOLS=OFF -DCMAKE_INSTALL_PREFIX=..\..\build\x86
      working_direcotry: vs17-x86
    - run: cmake --build . --config Release --target install
      working_direcotry: vs17-x86
    - run: mkdir vs17-x64
    - run: cmake .. -G "Visual Studio 17 2022" -A x64   -DAUTO_OPTIMIZE=OFF -DSW_BUILD=OFF -DBUILD_TRAINING_TOOLS=OFF -DCMAKE_INSTALL_PREFIX=..\..\build\x64
      working_direcotry: vs17-x64
    - run: cmake --build . --config Release --target install
      working_direcotry: vs17-x64
