name: Build dependencies

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
defaults:
  run:
    shell: cmd

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - run: vcpkg install giflib:x86-windows-static libjpeg-turbo:x86-windows-static liblzma:x86-windows-static libpng:x86-windows-static tiff:x86-windows-static zlib:x86-windows-static
    - run: vcpkg install giflib:x64-windows-static libjpeg-turbo:x64-windows-static liblzma:x64-windows-static libpng:x64-windows-static tiff:x64-windows-static zlib:x64-windows-static
    - uses: actions/checkout@v4
      with:
        repository: DanBloomberg/leptonica
        ref: 1.82.0
        path: leptonica
    - run: mkdir .\leptonica\vs17-x86\
    - run: cmake .. -G "Visual Studio 17 2022" -A Win32 -DSW_BUILD=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows-static -DCMAKE_INSTALL_PREFIX=..\..\build\x86
      working-directory: .\leptonica\vs17-x86\
    - run: cmake --build . --config Release --target install
      working-directory: .\leptonica\vs17-x86\
    - run: mkdir .\leptonica\vs17-x64\
    - run: cmake .. -G "Visual Studio 17 2022" -A x64 -DSW_BUILD=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_INSTALL_PREFIX=..\..\build\x64
      working-directory: .\leptonica\vs17-x64\
    - run: cmake --build . --config Release --target install
      working-directory: .\leptonica\vs17-x64\
    - uses: actions/checkout@v4
      with:
        repository: tesseract-ocr/tesseract
        ref: 5.2.0
        path: tesseract
    - run: mkdir .\tesseract\vs17-x86\
    - run: cmake .. -G "Visual Studio 17 2022" -A Win32 -DAUTO_OPTIMIZE=OFF -DSW_BUILD=OFF -DBUILD_TRAINING_TOOLS=OFF -DCMAKE_INSTALL_PREFIX=..\..\build\x86
      working-directory: .\tesseract\vs17-x86\
    - run: cmake --build . --config Release --target install
      working-directory: .\tesseract\vs17-x86\
    - run: mkdir .\tesseract\vs17-x64\
    - run: cmake .. -G "Visual Studio 17 2022" -A x64   -DAUTO_OPTIMIZE=OFF -DSW_BUILD=OFF -DBUILD_TRAINING_TOOLS=OFF -DCMAKE_INSTALL_PREFIX=..\..\build\x64
      working-directory: .\tesseract\vs17-x64\
    - run: cmake --build . --config Release --target install
      working-directory: .\tesseract\vs17-x64\
