name: Build dependencies

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
defaults:
  run:
    shell: cmd

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - name: Install x86 dependencies
      run: vcpkg install giflib:x86-windows-static jbigkit:x86-windows-static libjpeg-turbo:x86-windows-static liblzma:x86-windows-static libpng:x86-windows-static libwebp:x86-windows-static openjpeg:x86-windows-static tiff:x86-windows-static zlib-ng:x86-windows-static zstd:x86-windows-static
    - name: Install x64 dependencies
      run: vcpkg install giflib:x64-windows-static jbigkit:x64-windows-static libjpeg-turbo:x64-windows-static liblzma:x64-windows-static libpng:x64-windows-static libwebp:x64-windows-static openjpeg:x64-windows-static tiff:x64-windows-static zlib-ng:x64-windows-static zstd:x64-windows-static
    - name: Checkout Leptonica
      uses: actions/checkout@v4
      with:
        repository: DanBloomberg/leptonica
        ref: 1.84.1
        path: leptonica
    - name: Build Leptonica x86
      run: |
        mkdir vs17-x86
        cd vs17-x86
        cmake .. -G "Visual Studio 17 2022" -A Win32 -DSW_BUILD=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows-static -DCMAKE_INSTALL_PREFIX=..\..\build\x86
        cmake --build . --config Release --target install
      working-directory: leptonica
    - name: Build Leptonica x64
      run: |
        mkdir vs17-x64
        cd vs17-x64
        cmake .. -G "Visual Studio 17 2022" -A x64 -DSW_BUILD=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_INSTALL_PREFIX=..\..\build\x64
        cmake --build . --config Release --target install\
      working-directory: leptonica
    - name: Checkout Tesseract
      uses: actions/checkout@v4
      with:
        repository: tesseract-ocr/tesseract
        ref: 5.3.4
        path: tesseract
    - name: Build Tesseract x86
      run: |
        mkdir vs17-x86
        cd vs17-x86
        cmake .. -G "Visual Studio 17 2022" -A Win32 -DAUTO_OPTIMIZE=OFF -DSW_BUILD=OFF -DBUILD_TRAINING_TOOLS=OFF -DCMAKE_INSTALL_PREFIX=..\..\build\x86
        cmake --build . --config Release --target install
      working-directory: tesseract
    - name: Create Tesseract x64 output directory
      run: mkdir .\tesseract\vs17-x64\
    - name: Build Tesseract x86
      run: |
        mkdir vs17-x64
        cd vs17-x64
        cmake .. -G "Visual Studio 17 2022" -A x64 -DAUTO_OPTIMIZE=OFF -DSW_BUILD=OFF -DBUILD_TRAINING_TOOLS=OFF -DCMAKE_INSTALL_PREFIX=..\..\build\x64
        cmake --build . --config Release --target install
      working-directory: tesseract
    - name: Archive Leptonica x86
      uses: actions/upload-artifact@v4
      with:
        name: leptonica-x86
        path: leptonica\vs17-x86
    - name: Archive Leptonica x64
      uses: actions/upload-artifact@v4
      with:
        name: leptonica-x64
        path: leptonica\vs17-x64
    - name: Archive Tesseract x86
      uses: actions/upload-artifact@v4
      with:
        name: tesseract-x86
        path: tesseract\vs17-x86
    - name: Archive Tesseract x64
      uses: actions/upload-artifact@v4
      with:
        name: tesseract-x64
        path: tesseract\vs17-x64
