name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: build-and-test-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install Ubuntu dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update &&
        sudo apt-get install -y tesseract-ocr libleptonica-dev && 
        ls -la /usr/local/lib && 
        ls -la /usr/lib/x86_64-linux-gnu

    - name: Restore
      run: dotnet restore tesseract/src/Tesseract.sln
      
    - name: Build
      run: dotnet build --configuration Release --no-restore tesseract/src/Tesseract.sln
    
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --logger trx --results-directory "TestResults" tesseract/src/Tesseract.sln
    
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results
        path: TestResults
      if: ${{ always() }}
