name: cmake-win64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: cmd

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - name: Install zlib-ng
      run: vcpkg install zlib-ng:x64-windows-static
    - name: Install libpng
      run: libpng:x64-windows-static
    - name: Install giflib
      run: vcpkg install giflib:x64-windows-static
    - name: Install libjpeg
      run: vcpkg install libjpeg-turbo:x64-windows-static
    - name: Install openjpeg
      run: vcpkg install openjpeg:x64-windows-static
    - name: Install webp
      run: vcpkg install libwebp:x64-windows-static
    - name: Install jbigkit
      run: vcpkg install jbigkit:x64-windows-static
    - name: Install zstd
      run: vcpkg install zstd:x64-windows-static
    - name: Install lzma
      run: vcpkg install liblzma:x64-windows-static
    - name: Install libtiff
      run: vcpkg install tiff:x64-windows-static
    - name: Checkout Leptonica
      uses: actions/checkout@v4
      with:
        repository: DanBloomberg/leptonica
        ref: 1.84.1
        path: leptonica
    - name: Build Leptonica x64
      run: |
        mkdir vs17-x64
        cd vs17-x64
        cmake .. -G "Visual Studio 17 2022" -A x64 -DSW_BUILD=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_INSTALL_PREFIX=..\..\build\x64
        cmake --build . --config Release --target install
      working-directory: leptonica
    - name: Checkout Tesseract
      uses: actions/checkout@v4
      with:
        repository: tesseract-ocr/tesseract
        ref: 5.3.4
        path: tesseract
    - name: Build Tesseract x64
      run: |
        mkdir vs17-x64
        cd vs17-x64
        cmake .. -G "Visual Studio 17 2022" -A x64 -DAUTO_OPTIMIZE=OFF -DSW_BUILD=OFF -DBUILD_TRAINING_TOOLS=OFF -DCMAKE_INSTALL_PREFIX=..\..\build\x64
        cmake --build . --config Release --target install
      working-directory: tesseract
    - name: Archive Leptonica x64
      uses: actions/upload-artifact@v4
      with:
        name: leptonica-x64
        path: leptonica\vs17-x64
    - name: Archive Tesseract x64
      uses: actions/upload-artifact@v4
      with:
        name: tesseract-x64
        path: tesseract\vs17-x64
