name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - run: dotnet restore ./TestTesseract/TestTesseract.csproj
    - run: dotnet publish  ./TestTesseract/TestTesseract.csproj -c Release -o out
    - run: sudo add-apt-repository ppa:alex-p/tesseract-ocr-devel
    - run: sudo apt update
    - run: sudo apt install tesseract-ocr
    - run: sudo apt install libleptonica-dev
    - run: ls -lh /usr/lib/x86_64-linux-gnu
    - run: ln -s /usr/lib/x86_64-linux-gnu/liblept.so.5.0.4 ./out/x64/libleptonica-1.82.0.so
    - run: ln -s /usr/lib/x86_64-linux-gnu/libtesseract.so.5.0.3 ./out/x64/libtesseract50.so
    - run: ls out
    - run: dotnet TestTesseract.dll
      working-directory: out
    - name: Archive Leptonica
      uses: actions/upload-artifact@v4
      with:
        name: leptonica-latest
        path: /usr/lib/x86_64-linux-gnu/liblept.so.5.0.4
    - name: Archive Tesseract
      uses: actions/upload-artifact@v4
      with:
        name: tesseract-latest
        path: /usr/lib/x86_64-linux-gnu/libtesseract.so.5.0.3
