# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - run: sudo apt install tesseract-ocr
    - run: sudo apt install libtesseract-dev
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - run: dotnet publish -c Release
      working-directory: ./TestTesseract
    - run: ln -s /usr/lib/x86_64-linux-gnu/liblept.so.5 ./TestTesseract/bin/Release/net6.0/publish/x64/libleptonica-1.80.0.so
    - run: ln -s /usr/lib/x86_64-linux-gnu/libtesseract.so.4 ./TestTesseract/bin/Release/net6.0/publish/x64/libtesseract41.so
    - run: ls
      working-directory: ./TestTesseract/bin/Release/net6.0/publish
    - run: ls
      working-directory: ./TestTesseract/bin/Release/net6.0/publish/tessdata
    - name: Run
      run: dotnet ./TestTesseract/bin/Release/net6.0/publish/TestTesseract.dll
