name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - run: dotnet restore ./TestTesseract/TestTesseract.csproj
    - run: dotnet publish  ./TestTesseract/TestTesseract.csproj -c Release -o out
    - run: sudo apt update
    - run: sudo apt install libleptonica-dev
    - run: sudo apt install tesseract-ocr
    - run: ln -s /usr/lib/x86_64-linux-gnu/liblept.so ./out/x64/libleptonica-1.82.0.so
    - run: ln -s /usr/lib/x86_64-linux-gnu/libtesseract.so ./out/x64/libtesseract50.so
    - run: dotnet ./out/TestTesseract.dll
