# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - run: dotnet restore ./TestTesseract/TestTesseract.csproj
    - run: dotnet publish  ./TestTesseract/TestTesseract.csproj -c Release -o out
    - run: sudo apt update
    - run: sudo apt install tesseract-ocr
    - run: sudo apt install libtesseract-dev
    - run: ls
      working-directory: ./out
    - run: ln -s /usr/lib/x86_64-linux-gnu/liblept.so.5 ./out/x64/libleptonica-1.82.0.so
    - run: ln -s /usr/lib/x86_64-linux-gnu/libtesseract.so.5 ./out/x64/libtesseract50.so
    - run: dotnet ./TestTesseract/bin/Release/net8.0/publish/TestTesseract.dll
